apiVersion: v1
kind: Service
metadata:
  name: pod-deploy
  labels:
    name: pod-deploy
    app: pod-deploy
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: pod-deploy
    app: pod-deploy

