apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kubefirst-sts
spec:
  serviceName: "kubefirst-sts"
  replicas: 2
  selector:
    matchLabels:
      app: kubefirst-sts
  template:
    metadata:
      labels:
        app: kubefirst-sts
    spec:
      containers:
      - name: kubefirst-sts
        image: mertpolatt/kubefirst:v1
        ports:
        - containerPort: 80

